/*
CREATE DATABASE IF NOT EXISTS plano;
*/
/*MySql talves não esteja funcionando pois agr estamos banco de postgres

    CREATE TABLE IF NOT EXISTS USUARIO ( id int PRIMARY KEY AUTO_INCREMENT, sobrenome varchar(200), genero varchar(5), cpf int UNIQUE, dat_nasc date, senha varchar(500), nome varchar(200), id_Endereco int, FK_PERFIL_id int );
    CREATE TABLE IF NOT EXISTS ENDERECO ( id int PRIMARY KEY AUTO_INCREMENT, cep varchar(50), desc_logradouro varchar(300), num int, cidade varchar(200), uf varchar(5), id_Logradouro int, FK_LOGRADOURO_id int );
    CREATE TABLE IF NOT EXISTS LOGRADOURO ( id int PRIMARY KEY AUTO_INCREMENT, tp_logradouro varchar(100) );
    CREATE TABLE IF NOT EXISTS TIPO_CONTATO ( id int PRIMARY KEY AUTO_INCREMENT, tp_contato varchar(100) );
    CREATE TABLE IF NOT EXISTS PROFISSAO ( id int PRIMARY KEY AUTO_INCREMENT, descricao varchar(150) );
    CREATE TABLE TIPO_GASTO ( id int PRIMARY KEY AUTO_INCREMENT, desc_tpGasto varchar(150) );
    CREATE TABLE IF NOT EXISTS GASTO ( id int PRIMARY KEY AUTO_INCREMENT, valor float );
    CREATE TABLE IF NOT EXISTS PLANEJAMENTO ( id int PRIMARY KEY AUTO_INCREMENT, porcentagem int );
    CREATE TABLE IF NOT EXISTS PERFIL ( id int PRIMARY KEY AUTO_INCREMENT, perfil varchar(100) );
    CREATE TABLE IF NOT EXISTS RECOMENDACAO ( id int PRIMARY KEY AUTO_INCREMENT, descricao varchar(500) );
    CREATE TABLE IF NOT EXISTS Usuario_Endereco ( fk_USUARIO_id int, fk_ENDERECO_id int );
    CREATE TABLE IF NOT EXISTS Usuario_TpContato ( fk_USUARIO_id int, fk_TIPO_CONTATO_id int, descricao varchar(150) );
    CREATE TABLE IF NOT EXISTS Usuario_Profissao ( fk_USUARIO_id int, fk_PROFISSAO_id int, renda float, id int PRIMARY KEY AUTO_INCREMENT );
    CREATE TABLE IF NOT EXISTS Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO ( fk_TIPO_GASTO_id int, fk_USUARIO_id int, fk_GASTO_id int, fk_PLANEJAMENTO_id int );
    CREATE TABLE IF NOT EXISTS Perfil_Recomendacao ( fk_PERFIL_id int, fk_RECOMENDACAO_id int );
    ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_2 FOREIGN KEY (FK_PERFIL_id) REFERENCES PERFIL (id) ON DELETE SET NULL;
    ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_2 FOREIGN KEY (FK_LOGRADOURO_id) REFERENCES LOGRADOURO (id) ON DELETE CASCADE;
    ALTER TABLE Usuario_Endereco ADD CONSTRAINT FK_Usuario_Endereco_1 FOREIGN KEY (fk_USUARIO_id) REFERENCES USUARIO (id) ON DELETE SET NULL;
    ALTER TABLE Usuario_Endereco ADD CONSTRAINT FK_Usuario_Endereco_2 FOREIGN KEY (fk_ENDERECO_id) REFERENCES ENDERECO (id) ON DELETE SET NULL;
    ALTER TABLE Usuario_TpContato ADD CONSTRAINT FK_Usuario_TpContato_1 FOREIGN KEY (fk_USUARIO_id) REFERENCES USUARIO (id) ON DELETE SET NULL;
    ALTER TABLE Usuario_TpContato ADD CONSTRAINT FK_Usuario_TpContato_2 FOREIGN KEY (fk_TIPO_CONTATO_id) REFERENCES TIPO_CONTATO (id) ON DELETE SET NULL;
    ALTER TABLE Usuario_Profissao ADD CONSTRAINT FK_Usuario_Profissao_2 FOREIGN KEY (fk_USUARIO_id) REFERENCES USUARIO (id) ON DELETE SET NULL;
    ALTER TABLE Usuario_Profissao ADD CONSTRAINT FK_Usuario_Profissao_3 FOREIGN KEY (fk_PROFISSAO_id) REFERENCES PROFISSAO (id) ON DELETE SET NULL;
    ALTER TABLE Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO ADD CONSTRAINT FK_Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO_1 FOREIGN KEY (fk_TIPO_GASTO_id) REFERENCES TIPO_GASTO (id) ON DELETE NO ACTION;
    ALTER TABLE Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO ADD CONSTRAINT FK_Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO_2 FOREIGN KEY (fk_USUARIO_id) REFERENCES USUARIO (id) ON DELETE NO ACTION;
    ALTER TABLE Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO ADD CONSTRAINT FK_Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO_3 FOREIGN KEY (fk_GASTO_id) REFERENCES GASTO (id) ON DELETE NO ACTION;
    ALTER TABLE Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO ADD CONSTRAINT FK_Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO_4 FOREIGN KEY (fk_PLANEJAMENTO_id) REFERENCES PLANEJAMENTO (id) ON DELETE NO ACTION;
    ALTER TABLE Perfil_Recomendacao ADD CONSTRAINT FK_Perfil_Recomendacao_1 FOREIGN KEY (fk_PERFIL_id) REFERENCES PERFIL (id) ON DELETE SET NULL;
    ALTER TABLE Perfil_Recomendacao ADD CONSTRAINT FK_Perfil_Recomendacao_2 FOREIGN KEY (fk_RECOMENDACAO_id) REFERENCES RECOMENDACAO (id) ON DELETE SET NULL;
*/

/*correto POSTGRES*/
CREATE TABLE IF NOT EXISTS USUARIO ( id SERIAL PRIMARY KEY, sobrenome varchar(200), genero varchar(5), cpf varchar(20) UNIQUE, nascimento date, senha varchar(500), nome varchar(200), email varchar(200), FK_PERFIL_id int );

CREATE TABLE IF NOT EXISTS ENDERECO ( id SERIAL PRIMARY KEY, cep varchar(50), desc_logradouro varchar(300), num int, cidade varchar(200), uf varchar(5), id_Logradouro int, FK_LOGRADOURO_id int );

CREATE TABLE IF NOT EXISTS LOGRADOURO ( id SERIAL PRIMARY KEY, tp_logradouro varchar(100) );

CREATE TABLE IF NOT EXISTS TIPO_CONTATO ( id SERIAL PRIMARY KEY, tp_contato varchar(100) );

CREATE TABLE IF NOT EXISTS PROFISSAO ( id SERIAL PRIMARY KEY, descricao varchar(150) );

CREATE TABLE IF NOT EXISTS TIPO_GASTO ( id SERIAL PRIMARY KEY, desc_tpGasto varchar(150) );

CREATE TABLE IF NOT EXISTS GASTO ( id SERIAL PRIMARY KEY, valor float );

CREATE TABLE IF NOT EXISTS PLANEJAMENTO ( id SERIAL PRIMARY KEY, porcentagem int );

CREATE TABLE IF NOT EXISTS PERFIL ( id SERIAL PRIMARY KEY, perfil varchar(100) );

CREATE TABLE IF NOT EXISTS RECOMENDACAO ( id SERIAL PRIMARY KEY, descricao varchar(500) );

CREATE TABLE IF NOT EXISTS Usuario_Endereco ( fk_USUARIO_id int, fk_ENDERECO_id int );

CREATE TABLE IF NOT EXISTS Usuario_TpContato ( fk_USUARIO_id int, fk_TIPO_CONTATO_id int, descricao varchar(150) );

CREATE TABLE IF NOT EXISTS Usuario_Profissao ( fk_USUARIO_id int, fk_PROFISSAO_id int, renda float, id SERIAL PRIMARY KEY );

CREATE TABLE IF NOT EXISTS Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO ( fk_TIPO_GASTO_id int, fk_USUARIO_id int, fk_GASTO_id int, fk_PLANEJAMENTO_id int );

CREATE TABLE IF NOT EXISTS Perfil_Recomendacao ( fk_PERFIL_id int, fk_RECOMENDACAO_id int );

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_2 FOREIGN KEY (FK_PERFIL_id) REFERENCES PERFIL (id) ON DELETE SET NULL;

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_2 FOREIGN KEY (FK_LOGRADOURO_id) REFERENCES LOGRADOURO (id) ON DELETE CASCADE;

ALTER TABLE Usuario_Endereco ADD CONSTRAINT FK_Usuario_Endereco_1 FOREIGN KEY (fk_USUARIO_id) REFERENCES USUARIO (id) ON DELETE SET NULL;

ALTER TABLE Usuario_Endereco ADD CONSTRAINT FK_Usuario_Endereco_2 FOREIGN KEY (fk_ENDERECO_id) REFERENCES ENDERECO (id) ON DELETE SET NULL;

ALTER TABLE Usuario_TpContato ADD CONSTRAINT FK_Usuario_TpContato_1 FOREIGN KEY (fk_USUARIO_id) REFERENCES USUARIO (id) ON DELETE SET NULL;

ALTER TABLE Usuario_TpContato ADD CONSTRAINT FK_Usuario_TpContato_2 FOREIGN KEY (fk_TIPO_CONTATO_id) REFERENCES TIPO_CONTATO (id) ON DELETE SET NULL;

ALTER TABLE Usuario_Profissao ADD CONSTRAINT FK_Usuario_Profissao_2 FOREIGN KEY (fk_USUARIO_id) REFERENCES USUARIO (id) ON DELETE SET NULL;

ALTER TABLE Usuario_Profissao ADD CONSTRAINT FK_Usuario_Profissao_3 FOREIGN KEY (fk_PROFISSAO_id) REFERENCES PROFISSAO (id) ON DELETE SET NULL;

ALTER TABLE Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO ADD CONSTRAINT FK_Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO_1 FOREIGN KEY (fk_TIPO_GASTO_id) REFERENCES TIPO_GASTO (id) ON DELETE NO ACTION;

ALTER TABLE Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO ADD CONSTRAINT FK_Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO_2 FOREIGN KEY (fk_USUARIO_id) REFERENCES USUARIO (id) ON DELETE NO ACTION;

ALTER TABLE Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO ADD CONSTRAINT FK_Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO_3 FOREIGN KEY (fk_GASTO_id) REFERENCES GASTO (id) ON DELETE NO ACTION;

ALTER TABLE Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO ADD CONSTRAINT FK_Usuario_TpGasto_TIPO_GASTO_USUARIO_GASTO_PLANEJAMENTO_4 FOREIGN KEY (fk_PLANEJAMENTO_id) REFERENCES PLANEJAMENTO (id) ON DELETE NO ACTION;

ALTER TABLE Perfil_Recomendacao ADD CONSTRAINT FK_Perfil_Recomendacao_1 FOREIGN KEY (fk_PERFIL_id) REFERENCES PERFIL (id) ON DELETE SET NULL;

ALTER TABLE Perfil_Recomendacao ADD CONSTRAINT FK_Perfil_Recomendacao_2 FOREIGN KEY (fk_RECOMENDACAO_id) REFERENCES RECOMENDACAO (id) ON DELETE SET NULL;